### PR TITLE
Loader Menu Reorder - Third time's a charm

### PR DESCRIPTION
**Pull request by ESurge**
- Loader menu loads `FLIPPER_APPS`, `ExtMainApps` list, then finally manually added items with `Settings` first, and `Applications` last.
- `Clock` app is first selected when opening main menu

Notes:
- Don't commit when tired
- Brought `Settings` down to `Applications` for easier loop logic, but this can be changed to have `Settings` back up with `CFW Settings` if needed/wanted

### CODE REVIEW

**Comment by RogueMaster** [comment]
Is this the order?
{
        "Clock",
        "Sub-GHz",
        "Sub-GHz Remote",
        "Sub-GHz Playlist",
        "125 kHz RFID",
        "NFC",
        "Infrared",
        "IR Remote",
        "GPIO",
        "iButton",
        "Bad USB",
        "U2F",
        "CFW Settings",
        "Settings",
        "Applications"}

**Comment by RogueMaster** [comment]
This code has MANUALLY_ADDED_ITEMS_COUNT  which would not be implemented this way since its custom... Ideally, it counts the favorites added...

**Comment by RogueMaster** [comment]
Or is MANUALLY_ADDED_ITEMS_COUNT  Settings and Applications?

**Comment by ESurge** [comment]
`MANUALLY_ADDED_ITEMS_COUNT` is for `Applications` and `Settings` because these are added to the menu in a static way. Perhaps this should be renamed to `STATIC_ITEMS_COUNT`

It's needs to be added to `total_items` in order for the menu loop to add `Applications` and `Settings`

So the order would be:
- Clock
- Sub-Ghz
- Sub-GHz Remote
- Sub-GHz Playlist
- 125kHz RFID
- NFC
- Infrared
- IR Remote
- GPIO
- iButton
- Bad USB
- U2F
- CFW Settings
- External apps added by CFW Settings
- Settings
- Applocations

**Pull request merged**
