### PR TITLE
Extended frequency range flags

### PR DESCRIPTION
**Pull request by tkerby**
# What's new

- Increased frequency limits to match those to the unofficial range of Yard Stick One. This allows the use of the SubGhz files for restaurant paging systems and others to work. Note that this is an unofficially supported frequency, and the device needs to be region unlocked for this to work. It's at your own risk as developers have raised concerns that there may be damage outside official ranges, although it's most likely ok. Yard Stick One devs noted the only problem they saw was with failure of the PLL to lock but no damage to the transceivers and no problems at all with a larger range than on the datasheet. This mod falls within their extended unofficial range.

To get the extended range you need to add an additional subghz settings file to enable it with a Boolean to turn it on. Read the source code to work out the file name and flag name!

# Notes

It would have been nice to add an additional bool to settings_user but unfortunately trying to read a non-existent bool seems to hang the FZ app system. This means we would have to make the setting visible and set to false. The best way to hide a function is to add an additional settings file on the as card as if it's not there it can be ignored 

# Verification 

- Tested using an SDR. PLL remains locked and transmits correctly

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
Please do continue using this and we can revisit in some time to see if any damage is caused by this change. If not, will consider merging after a few months time.

**Comment by tkerby** [comment]
Is there an easy way to add a flag in the settings file that could be used here? Thinking in the same way the region unlock is turned off

**Comment by RocketGod-git** [comment]
> Please do continue using this and we can revisit in some time to see if any damage is caused by this change. If not, will consider merging after a few months time.

I'm also testing... no issues so far but I'll keep you posted. I'm RocketGod on Discord.

**Comment by RocketGod-git** [comment]
https://github.com/jeremyyablan/DangerZone

**Comment by sweeper1** [comment]
Agreed that a settings flag similar to the region unlock with a warning / YMMV statement would be great

**Comment by tkerby** [comment]
So I've managed to get a flag working but there seems to be a bug in that the app will crash if the flag doesn't exist in the settings file - ie it must be there with a true/false

I'd far rather hide the option from the settings so users have to explicitly know what to add rather than leaving it there set to false

**Comment by KairuByte** [comment]
If the setting is required, and this cannot be worked around, use a setting name that is daunting.

`potentiallyDestroyYourFlipper = false` for example.

**Comment by tkerby** [comment]
> If the setting is required, and this cannot be worked around, use a setting name that is daunting.
> 
> 
> 
> `potentiallyDestroyYourFlipper = false` for example.

That's the plan - there is an appropriately named file and flag. You need to find the names in the source by looking at the code or this PR to enable. I'd suggest we don't distribute the settings file by default.

**Comment by sweeper1** [comment]
@tkerby It looks like the code comments show the flag needing to be set in setting_user (line 259) but line 269 looks like it's checking extend_range

**Pull request merged**
