### PR TITLE
Add Mifare Fuzzer Keys

### PR DESCRIPTION
**Pull request by OrionW06**
# What's new

I've added Mifare Fuzzer Keys to the app's resources so that it's more useful out the box

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [X] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by OrionW06** [comment]
This should be usable against a large chunk of MIFARE tags, I find it of great use :)

**Comment by OrionW06** [comment]
Aww, why'd you close it? :(

**Comment by RogueMaster** [comment]
> Aww, why'd you close it? :(

See Files Changed Count @OrionW06

**Comment by RogueMaster** [comment]
It seems the sheer size of your proposed changes are a mere reason to decline

**Comment by OrionW06** [comment]
I just had a lot of keys to add, I can remove some if need be.

**Comment by OrionW06** [comment]
Alrighty, so I've deleted over half of the keyfiles (each of which are only 50 mb to not wreck the RAM on the flipper), confirmed working on my end.

**Comment by RogueMaster** [comment]
> Alrighty, so I've deleted over half of the keyfiles (each of which are only 50 mb to not wreck the RAM on the flipper), confirmed working on my end.

Sorry this PR will not be accepted

**Pull request closed without merging**
