### PR TITLE
Add rfid_fuzzer plugin

### PR DESCRIPTION
**Pull request by Ganapati**
Add new plugin for playing/fuzzing with EM4100 and rfid protocols

### CODE REVIEW

**Comment by RogueMaster** [comment]
Is a separate device needed for this or it works with Flipper RFID?

**Comment by Ganapati** [comment]
Nothing is needed, it use the internal rfid module.

**Comment by xMasterX** [comment]
Hi, have you seen what changes is coming?

https://github.com/flipperdevices/flipperzero-firmware/pull/1601

App will need some changes to be able to work after new lfrfid system will be merged in official dev


also for note, [eng1n33r](https://github.com/Eng1n33r/flipperzero-firmware) fork is not abandoned, and I will be happy seeing your PR in future

**Comment by RogueMaster** [comment]
> [eng1n33r](https://github.com/Eng1n33r/flipperzero-firmware) fork is not abandoned

You update so frequently I would hope people don't think it's abandoned. 😄

**Comment by rct31** [comment]
Hi, 
Is it possible to start from a uid decided by the user ? 

Per haps also to stop rolling the uid and save the current uid when the gates opens ?

**Comment by Ganapati** [comment]
It require to make a good user interface and I suck at this. Seriously, if you can, i'll be happy to help integrating it !

**Comment by azaitsev** [comment]
Could you add an ability to switch ID's manually by pressing button, not automatically?

**Comment by normancomics** [comment]
Flipper zero .tgz

**Pull request merged**
