### PR TITLE
Wifi marauder

### PR DESCRIPTION
**Pull request by chazp246**
# What's new

- Added costum wifi icon for wifi marauder companion app. 
 # WILL DO (soon?)
- I will be making new marauder companion with gui soo its more easy to use without the need to jump milion times.

# Verification 

- The icon should change from default IR icon to the new one
- I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
Hi, thank you for your submission, I look forward to your future work on the marauder app. We are trying to conserve space and this icon asset is not too different than the infrared one currently in use (which does the job). Therefore, keeping it to what is present to conserve free space.

**Comment by Einstein2150** [comment]
@chazp246 is it possible to use wifi marauder with an esp8266 board or only with the official (esp32) breakout board?

**Comment by chazp246** [comment]
> @chazp246 is it possible to use wifi marauder with an esp8266 board or only with the official (esp32) breakout board?

I do not think marauder works with esp8266 (can be wrong). But you could use dstike deauther project with some changes to the companion app. I think it should be doable. You DO NOT need the official wifi devboard. I am currently using ESP32-S2 dev board and it works just the same. Be carefull that you need ESP32-S2 for marauder because S1 does not work with all the features (if at all). The only thing you need to do is to flash esp32 with the marauder for flipper + make 4 connections. You need to connect GND for common ground, RX and TX. If you want to power it from the flipper and not a outside source connect also the 5V. It will not power on right away. You need to go to GPIO and turn on 5V. In the new version of the app i will make it turn on the ESP32 once you open the app soo it will be easier.

EDIT::: IT works on S1, its even better.... sorry for misleading

**Comment by chazp246** [comment]
> Hi, thank you for your submission, I look forward to your future work on the marauder app. We are trying to conserve space and this icon asset is not too different than the infrared one currently in use (which does the job). Therefore, keeping it to what is present to conserve free space.

Ahh okay np. Is there currently no way to store the icons on the SD card? Also where i can find all of used space in my CPU?

**Comment by Einstein2150** [comment]
> > @chazp246 is it possible to use wifi marauder with an esp8266 board or only with the official (esp32) breakout board?
> 
> I do not think marauder works with esp8266 (can be wrong). But you could use dstike deauther project with some changes to the companion app. I think it should be doable. You DO NOT need the official wifi devboard. I am currently using ESP32-S2 dev board and it works just the same. Be carefull that you need ESP32-S2 for marauder because S1 does not work with all the features (if at all). The only thing you need to do is to flash esp32 with the marauder for flipper + make 4 connections. You need to connect GND for common ground, RX and TX. If you want to power it from the flipper and not a outside source connect also the 5V. It will not power on right away. You need to go to GPIO and turn on 5V. In the new version of the app i will make it turn on the ESP32 once you open the app soo it will be easier.
> 
> EDIT::: IT works on S1, its even better.... sorry for misleading

I played a bit around and flashed the legendary spacehuhn deauther firmware to my esp8266 from [https://github.com/SpacehuhnTech/esp8266_deauther](https://github.com/SpacehuhnTech/esp8266_deauther ). I can control it with marauder - not good but it works when I modify the commands you prepared in marauder on the flipper.

I realized that marauder is only a serial monitor which sends commands to the wifi-board.

Is it possible that you implement the commands supported by the spacehuhn-deauther-firmware? You can find all supported commands here: [https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/serialcommands.md](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/serialcommands.md). Maybe we can make a all-in-one frontend for different wifi firmwares 😎

**Comment by chazp246** [comment]
> > > @chazp246 is it possible to use wifi marauder with an esp8266 board or only with the official (esp32) breakout board?
> > 
> > 
> > I do not think marauder works with esp8266 (can be wrong). But you could use dstike deauther project with some changes to the companion app. I think it should be doable. You DO NOT need the official wifi devboard. I am currently using ESP32-S2 dev board and it works just the same. Be carefull that you need ESP32-S2 for marauder because S1 does not work with all the features (if at all). The only thing you need to do is to flash esp32 with the marauder for flipper + make 4 connections. You need to connect GND for common ground, RX and TX. If you want to power it from the flipper and not a outside source connect also the 5V. It will not power on right away. You need to go to GPIO and turn on 5V. In the new version of the app i will make it turn on the ESP32 once you open the app soo it will be easier.
> > EDIT::: IT works on S1, its even better.... sorry for misleading
> 
> I played a bit around and flashed the legendary spacehuhn deauther firmware to my esp8266 from https://github.com/SpacehuhnTech/esp8266_deauther. I can control it with marauder - not good but it works when I modify the commands you prepared in marauder on the flipper.
> 
> I realized that marauder is only a serial monitor which sends commands to the wifi-board.
> 
> Is it possible that you implement the commands supported by the spacehuhn-deauther-firmware? You can find all supported commands here: https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/serialcommands.md. Maybe we can make a all-in-one frontend for different wifi firmwares 😎

I will be working on that next week. Once i get back. Also i am not the original creator of the marauder companion. I made new icon for the app and i will be working on better companion with proper gui.

**Pull request closed without merging**
