### PR TITLE
Finally the Actual Working Pull Request (SORRY!)

### PR DESCRIPTION
**Pull request by skizzophrenic**
# What's new

Removed the Left Icon bar and removed the shadow on battery icon

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
Did you update the animations again or are these updates pushing the old animation?

**Comment by skizzophrenic** [comment]
> 

They're the updated animations, I'm not sure why it looks like its pushing again.  I think you may have updated the animations right after I made the fork

**Comment by skizzophrenic** [comment]
I also just added a Tuning Fork app that was uploaded to main apps channel.  Removed the old Chip8 folder because it was causing compiling issues and it's broken/not updated in 10 months.

**Comment by RogueMaster** [comment]
I had already updated the animations recently, are these new updates (revision 3) or are these the wrong ones (revision 1)? Try to keep different features as different Pull Requests, makes for several branches to manage but easier to accept certain changes... I already added the gui changes so the only new item is the tuning fork app I think.

**Comment by skizzophrenic** [comment]
That's correct!

**Comment by skizzophrenic** [comment]
the animations on this pull request are correct.  I don't know what was up with the last one.  This PR was supposed to just be the new tuning fork and removing the broken chip8 application that was causing compiling errors

**Pull request merged**
