### PR TITLE
[IdleShutdown] Don't reload the settings every second

### PR DESCRIPTION
**Pull request by lokiuox**
# What's new

The current implementation of the "Shutdown on Idle" features reloads the power settings file every second to check for changes in the settings. (The `auto_shutdown_update()` [is called inside the main power service loop](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/e631285ff3620c06a68db0aaddab1fd065b3a13a/applications/services/power/power_service/power.c#L342)). This behaviour is also verifiable by checking the logs from the serial console, since they get spammed by `[I][SavedStruct] Loading "/int/.power.settings"`messages.    

This behavior is wasteful and could be detrimental on the internal memory. The simplest solution to fix this (implemented here) is to just reboot the Flipper when the setting is changed from the menu, i.e. the same thing that happens when the battery style is changed. The Flipper will just reload the new config on the next boot and no continuous checks are needed.    

# Verification 

Monitor the logs from the serial console to verify that the Loading calls are no more being spammed every second.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
Thank you!

**Comment by RogueMaster** [comment]
Can you check if this is still an issue with the latest changes from the original PR, and refix if necessary? @lokiuox  https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/420/0.69.1-1018-RM-0303.tgz

**Comment by lokiuox** [comment]
I tested the new release and it works correctly, no other fixes are necessary

**Comment by RogueMaster** [comment]
TY!

**Pull request merged**
