### PR TITLE
SD info dynamic units

### PR DESCRIPTION
**Pull request by non-bin**
# What's new

- Make units in SD info page dunamic (KB/MB/GB)
- Add free percentage too

# Verification 

- Compiled and loaded

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by non-bin** [comment]
havent tested MB

**Comment by RogueMaster** [comment]
Considered pushing this to OFW?

**Comment by non-bin** [comment]
If you mean the stock firmare, that's a good idea, and I just did

**Comment by RogueMaster** [comment]
Could you give the result more precision, like to 3 decimal places?... oddly it says my SD card is 55 GB Total, 58 GB Free

**Comment by non-bin** [comment]
Huh, yeah I'll do that, can you post the results without this change? (In KB)

**Review by non-bin — COMMENTED** [review]
Da fix total/free, add decimals

**Pull request merged**
