### PR TITLE
Auto detect raw unleashed

### PR DESCRIPTION
**Pull request by perspecdev**
# What's new

- Added ability to auto-detect raw signals in Sub-GHz -> Read

# Verification 

- Visit SubGHz -> Read, go to Config, and set Detect Raw to On, then back out of the config screen. Play a signal from another device that the Flipper doesn't know the protocol for. The raw signal should be detected and listed (e.g. "Raw 433.92") and you should be able to be save it.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
So the resolution for this was that "Auto detect raw" uses RAM and can cause issues storing stuff in RAM?

**Comment by perspecdev** [comment]
With my first PR to OFW, they had trouble getting it to detect the signal they were playing.  I made a few changes in order to resolve that and updated the PR.  One of the changes was increasing the amount of RAM allocated when you turn on the Detect Raw feature, since I believe they were running into an issue where the signal they were playing used more RAM than I had initially allocated in the code.  Raw recordings take up much more memory than key code recordings because they store every raw sample instead of just the bytes actually used by the protocol (keeloq, secplus, etc).

In the Read RAW feature, they overcome this issue by only storing a little in RAM and writing to disk as RAM fills up, then they store a little more in RAM, then write that to disk, and so on.  I didn't take that approach because it means writing a file to disk every time you detect a raw signal, and that didn't seem appropriate in Read mode where you could potentially read 99 raw signals.  The device has 256 KB of memory.  With my implementation, it allocates just over 2 KB when you turn on Detect Raw, and an additional 2 KB for each additional raw file it detects.  So it's technically possible to make it use up all the RAM on the device if you leave it running for a long time and if all the raw recordings it detects are long ones.  If a raw recording is shorter, it will deallocate the 2 KB when it gets detected and then only allocate the needed RAM.  This was all necessary in order to capture raw signals of average length instead of just signals that are really short.

This increase in memory usage in order to make it work like that was in a separate commit.  I'm happy to do a PR here to add that in.  Or if you prefer to just pull the feature out, no hard feelings!

**Comment by perspecdev** [comment]
Oops I meant to say it allocates a little over 1 KB per raw signal detected.

**Comment by RogueMaster** [comment]
Ok, please PR to fix if you can 😄

**Comment by perspecdev** [comment]
Done!

**Comment by tkerby** [comment]
I'd actually like to see this as a separate app with direct write to disk and a sensitivity adjust (how much above the current noise floor triggers a recording). Use case is being able to leave it for 24h and try and capture everything. Would ideally then post process and try to decode captured data.

**Comment by RogueMaster** [comment]
That would be awesome. The files would need to get saved for that case instead of being in RAM.

Also, perhaps drop the captures in a folder for the given date, and name with date/fulltime/counter...

Would be happy to add if you create.

**Comment by RogueMaster** [comment]
@perspecdev Could you update to latest changes and re-push this feature if it isn't too much trouble? 😄

**Comment by perspecdev** [comment]
Sure.  Hopefully I'll have a chance to get to it today, but not sure yet.

**Comment by RogueMaster** [comment]
I know the feeling, thank you for your help! Do when it best suits your schedule.

**Comment by tkerby** [comment]
@perspecdev if you need a hand testing any changes then happy to try the updates when you get a chance to look at this. Raw capture has been really useful

**Comment by perspecdev** [comment]
Thanks!  Sorry it's taking me so long to get to this.  Things got pretty busy for me.  I'm really wanting to get this done.  Hopeful I'll have a chance real soon.

**Comment by perspecdev** [comment]
PR submitted over here (with important comment):
https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/152

**Pull request merged**
