### PR TITLE
re-implemented auto-detect raw

### PR DESCRIPTION
**Pull request by perspecdev**
Added auto-detect raw back.  It runs without errors, but I'm not 100% confident it's capturing properly.  Maybe someone wants to test?

### CODE REVIEW

**Comment by RogueMaster** [comment]
Thank you!

**Comment by tkerby** [comment]
Tested over lunch. I'm managing to capture raw ok, although possibly less than before (has the threshold changed?) Seems to hop slower, so its obviously seeing signals but doesn't necessarily list a raw.

One problem I have found is if you attempt to send a raw signal from the captures without saving, it causes your screen to blank and hard faults needing a reset

**Comment by perspecdev** [comment]
> Tested over lunch. I'm managing to capture raw ok, although possibly less than before (has the threshold changed?) Seems to hop slower, so its obviously seeing signals but doesn't necessarily list a raw.
> 
> One problem I have found is if you attempt to send a raw signal from the captures without saving, it causes your screen to blank and hard faults needing a reset

Thanks for testing it out.  The threshold hasn't changed, but there does seem to be something going on with subghz in general.  It seems slower than it used to be, and that would definitely affect the ability to pick up raw signals (or even known signal types).  It's likely to miss some signals when it's slow because the signals may be gone by the time the code loops back around for the next check.

I had removed the pre-save send button before because that part isn't implemented yet.  I must have missed taking that out this time around.

**Comment by RogueMaster** [comment]
Would removing that pre-save send for unsaved raw fix the crashing issue people are having? Please PR if you can 😄 

I had some issues importing the code and had to fiddle with it but it seems to be in and working now... wanted to also keep the file dating that I overwrote at some point it seems...

**Comment by perspecdev** [comment]
I just realized that this PR uses some of my older code for auto-detecting raw.  I'll submit a PR later to update it and to remove that send button.

**Comment by perspecdev** [comment]
Actually, scratch that.  It's using the latest code.  But the send button does need to be removed.  Working on it...

**Pull request merged**
