### PR TITLE
Added ability to type spaces with the input keyboard

### PR DESCRIPTION
**Pull request by Maycuz**
Added ability to type spaces with the input keyboard by long-pressing `_`.

# What's new

- You can now input a space by long-pressing `_` (comparable to how you type uppercase letters).

# Verification 

- Open any input field (i.e. rename a SubGHz file).
- Long-press `_`.
- A space will be added to the input field.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by Maycuz** [comment]
Note, was contemplating using the "_" character instead of backspace. Can be changed to that if it makes more sense.

**Comment by RogueMaster** [comment]
So changing backspace to space? So how do you backspace? If you want to add a space you need a space key.

**Comment by RogueMaster** [comment]
Oh long press. I see nevermind

**Comment by RogueMaster** [comment]
Yeah do it on _ makes more sense

**Comment by RogueMaster** [comment]
Note this is probably introducing bugs with spaces in file names but those should be fixed anyhow or user needs to not name things with spaces. This is useful if we add a notepad type of app

**Comment by Maycuz** [comment]
Thanks, changing it to `_` !

> Note this is probably introducing bugs with spaces in file names but those should be fixed anyhow or user needs to not name things with spaces. This is useful if we add a notepad type of app

I added this specifically for the new Marauder functionality, which requires you to use spaces to change your settings (https://github.com/justcallmekoko/ESP32Marauder/wiki/settings-cmd). I have this functioning in my local branch (not committing the Marauder changes, I'll leave that up to the original author).

In my testing so far I have not encountered any issues related to spaces (save .sub with name containing spaces -> load it -> send it -> transfer it to host PC through qFlipper), though I might have missed a case where things break.

**Comment by RogueMaster** [comment]
Thank you!

**Comment by RogueMaster** [comment]
You should submit this to main branch you could be a 'contributor' on their discord

**Comment by Maycuz** [comment]
> You should submit this to main branch you could be a 'contributor' on their discord

Thanks for the tip, I'll give it a shot!

**Pull request merged**
